apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tourism-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/OletiSatishKumar/Devops_React_Infra_Repo.git'
    targetRevision: HEAD
    path: tourism-app
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tourism-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
